steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/postcard-server', '.']
  dir: 'server'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/postcard-server']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - beta
  - run
  - deploy
  - postcard-server
  - --image=gcr.io/$PROJECT_ID/postcard-server:latest
  - --region=us-central1
  - --platform=managed
    