swagger: '2.0'
info:
  title: Autfocus Endpoints
  version: 1.0.0
host: autofocus-api-vteoiajvqq-uc.a.run.app
schemes: 
  - https
produces:
  - application/json
paths:
  /postcards:
    put:
      summary: Replace postcard
      operationId: postcardsReplace
      x-google-backend:
        address: https://us-central1-autofocus.cloudfunctions.net/postcards
      consumes:
        - application/json
      parameters:
        - in: body
          name: postcard
          description: The new postcard
          schema:
            $ref: '#/definitions/Postcard'
      responses:
        '200':
          description: Successfully update postcard
          schema:
            $ref: '#/definitions/Postcard'
  
    post:
      summary: Insert postcard
      operationId: postcardsInsert
      x-google-backend:
        address: https://us-central1-autofocus.cloudfunctions.net/postcards
      consumes:
        - application/json
      parameters:
        - in: body
          name: postcard
          description: The new postcard
          schema:
            $ref: '#/definitions/Postcard'
      responses:
        '200':
          description: Successfully created postcard
          schema:
            $ref: '#/definitions/Postcard' 
    
    get:
      summary: Return postcards
      operationId: postcardsList
      x-google-backend:
        address: https://us-central1-autofocus.cloudfunctions.net/postcards
      responses:
        '200':
          description: Successfully returns list of postcards
          schema:
            type: array
            items:
              $ref: '#/definitions/Postcard'

definitions:
  Postcard:
    type: object
    properties:
      x:
        type: number
      y:
        type: number
      img:
        type: string
      comment:
        type: string